version: '3'
services:  
  postgres:
    image: "postgres:9.6.21"
    networks:
      - frontend
    ports:
      - "5432:5432"
    restart: always
    user: 1000:1000
    environment:
      - POSTGRES_USER=dinesh
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=dinesh-micro-apps
    volumes:
      - ./data:/var/lib/postgresql/data:z # persist data even if container shuts down
  
  # backend:
  #   image: "dineshsonachalam/gistify-backend:latest"
  #   environment:
  #     - GISTIFY_APP_ENV=${GISTIFY_APP_ENV}
  #     - GISTIFY_DEV_APP_URL=${GISTIFY_DEV_APP_URL}
  #     - GISTIFY_DEV_GITHUB_CLIENT_ID=${GISTIFY_DEV_GITHUB_CLIENT_ID}
  #     - GISTIFY_DEV_GITHUB_CLIENT_SECRET=${GISTIFY_DEV_GITHUB_CLIENT_SECRET}
  #     - GISTIFY_DEV_JWT_SECRET_KEY=${GISTIFY_DEV_JWT_SECRET_KEY}
  #     - GISTIFY_DEV_GIST_API_TOKEN=${GISTIFY_DEV_GIST_API_TOKEN}"
  #   networks:
  #     - frontend
  #   ports:
  #     - "8003:8003"
  #   depends_on:
  #     - postgres

networks:
  frontend:
