apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gistifyBackendSecrets.appName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData: 
  GISTIFY_APP_ENV: {{ .Values.gistifyBackendSecrets.GISTIFY_APP_ENV }}
  GISTIFY_PROD_APP_URL: {{ .Values.gistifyBackendSecrets.GISTIFY_PROD_APP_URL }}
  GISTIFY_PROD_GITHUB_CLIENT_ID: {{ .Values.gistifyBackendSecrets.GISTIFY_PROD_GITHUB_CLIENT_ID }}
  GISTIFY_PROD_GITHUB_CLIENT_SECRET: {{ .Values.gistifyBackendSecrets.GISTIFY_PROD_GITHUB_CLIENT_SECRET }}
  GISTIFY_PROD_JWT_SECRET_KEY: {{ .Values.gistifyBackendSecrets.GISTIFY_PROD_JWT_SECRET_KEY }}
  GISTIFY_PROD_GIST_API_TOKEN: {{ .Values.gistifyBackendSecrets.GISTIFY_PROD_GIST_API_TOKEN }}