apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.anyJsonBackendSecrets.appName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData: 
  GOANYJSON_APP_ENV: {{ .Values.anyJsonBackendSecrets.GOANYJSON_APP_ENV }}
  GOANYJSON_PROD_APP_URL: {{ .Values.anyJsonBackendSecrets.GOANYJSON_PROD_APP_URL }}
  GOANYJSON_PROD_GITHUB_CLIENT_ID: {{ .Values.anyJsonBackendSecrets.GOANYJSON_PROD_GITHUB_CLIENT_ID }}
  GOANYJSON_PROD_GITHUB_CLIENT_SECRET: {{ .Values.anyJsonBackendSecrets.GOANYJSON_PROD_GITHUB_CLIENT_SECRET }}
  GOANYJSON_PROD_JWT_SECRET_KEY: {{ .Values.anyJsonBackendSecrets.GOANYJSON_PROD_JWT_SECRET_KEY }}
  GOANYJSON_PROD_GIST_API_TOKEN: {{ .Values.anyJsonBackendSecrets.GOANYJSON_PROD_GIST_API_TOKEN }}