// Step 1: Create Action Types
export const UPDATE_IS_LOGGED_IN_STATUS = "UPDATE_IS_LOGGED_IN_STATUS";
export const UPDATE_USER_ID = "UPDATE_USER_ID";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_GISTS = "UPDATE_GISTS";