namespace: dinesh
replicas: 1

postgres:
    image: postgres:9.6.21
    containerPort: 5432
    appName: postgres
    volumeMountsName: postgres-data
    volumeMountsPath: /data/pgdata

gistifyBackend:
    image: dineshsonachalam/gistify-backend:latest
    containerPort: 8003
    appName: gistify-api
    ingressRoute: (Host(`api-gistify.dineshsonachalam.com`))

gistifyBackendSecrets:
    appName: gistify-secrets
    GISTIFY_APP_ENV: "PROD"
    GISTIFY_PROD_APP_URL: "https://gistify.dineshsonachalam.com/"
    GISTIFY_PROD_GITHUB_CLIENT_ID: "${GISTIFY_PROD_GITHUB_CLIENT_ID}"
    GISTIFY_PROD_GITHUB_CLIENT_SECRET: "${GISTIFY_PROD_GITHUB_CLIENT_SECRET}"
    GISTIFY_PROD_JWT_SECRET_KEY: "${GISTIFY_PROD_JWT_SECRET_KEY}"
    GISTIFY_PROD_GIST_API_TOKEN: "${GISTIFY_PROD_GIST_API_TOKEN}"

gistifyFrontend:
    image: dineshsonachalam/gistify-frontend:latest
    containerPort: 3000   
    appName: gistify-ui
    ingressRoute: (Host(`gistify.dineshsonachalam.com`))
