name: Docker

on:
  push:
    branches:    
      - '**'  # matches every branch
  
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Push image
        run: |
          pwd
          ls /home/runner/work/gistify/gistify/
          ls /home/runner/work/gistify/gistify/frontend/
          cat /home/runner/work/gistify/gistify/README.md
          
